services:
  autentication-backend:
    container_name: ${PROYECT_CONTEXT}-backend
    image: ${PROYECT_CONTEXT}-backend:0.1.0
    build: .
    restart: always
    environment:
      PORT: 80
      DATABASE_URL: $DATABASE_URL
      PRISMA_BINARY: '["debian-openssl-1.1.x"]'

    
