networks:
  sigue-adelante-radio:
    external: true

services:
  autentication-backend:
    container_name: sar-auth-backend
    image: sar-auth-backend:1.0.0
    build: .
    volumes:
      - ~/SigueAdelanteRadio/auth/secrets:/usr/app/generated/jwk
    restart: always
    networks:
      - sigue-adelante-radio
    environment:
      PORT: 80
      DATABASE_URL: $DATABASE_URL
      SECRET_SEED: $SECRET_SEED
    
